### ISSUE TITLE
brain_radius hardcoded to 50

### ISSUE THREAD

**Issue by arueter1** [DCAN-Labs/dcan_bold_processing#17]
Luci noticed that brain_radius appears to be hardcoded as 50 in a few places in DCANBOLDProc. For infant processing, we set brain_radius to 45 and it appears as though DBP overrides this because the FD values output by the pipeline match the values calculated using 50 mm. It would be nice if we could change the code to not override the input brain_radius so we could use this piece of code on infants.

**Comment by madisoth** [comment]
Reopening this issue; as noted in #28, `brain_radius` in dcan_bold_proc.py is not being passed to dcan_signal_processing and filtered_movement_regressors.

New PR (#29) is up to address this.

Quick FD comparison using infant-abcd-bids-pipeline (which passes in a brain radius = 45 mm to dcan_bold_proc.py)    


Using DBP v4.0.13:
<img width="603" alt="dbp_4013" src="https://github.com/user-attachments/assets/8489a4b0-89d7-4a17-96a1-a454c91134d3">

Using PR #29: 
<img width="676" alt="dbp_test" src="https://github.com/user-attachments/assets/71bc2467-389b-49c8-ae80-7a844543fd8a">

**Comment by LuciMoore** [comment]
addressed by PR https://github.com/DCAN-Labs/dcan_bold_processing/pull/29
