### ISSUE TITLE
Add metadata JSON for each major output

### ISSUE THREAD

**Issue by ericearl** [DCAN-Labs/dcan_bold_processing#2]
Talking with @kathy-snider we decided we will eliminate the DCANBOLDProc version-stamped output files of dcan_bold_processing (dtseries and ptseries, especially), instead opting for metadata JSON files which follow the BIDS standards for derivatives that include what options were used and how the files were generated.

**Comment by kweldon1** [comment]
This would necessitate a major lift from the XCPD team and thus not prioritized. Please submit another issue if it becomes one.
