### ISSUE TITLE
Processing done to Power atlas

### ISSUE THREAD

**Issue by tsalo** [DCAN-Labs/dcan_bold_processing#23]
I am trying to incorporate some of the atlases from this package into [XCP-D](https://github.com/PennLINC/xcp_d), by Dr. Fair's request. However, I'm a little confused about the Power atlas, which should have 264 ROIs, but only has 77 in [this file](https://github.com/DCAN-Labs/dcan_bold_processing/blob/6a4739bfa4580fd4593f6c786c539ba9c582779b/templates/parcellations/Power/fsLR/Power.32k_fs_LR.dlabel.nii). The [documentation I was pointed to](https://collection3165.readthedocs.io/en/stable/pipeline/#4-dbp-generation-of-parcellated-timeseries-for-specific-atlases) indicates that this should have all 264 spheres. Was there some processing done to the Power atlas that resulted in fewer ROIs? Also, does anyone know what the radius for the ROIs was set to?

**Comment by hough129** [comment]
@tsalo Apologies - I am just seeing this issue now. Did you get an answer to this question through other means?

**Comment by hough129** [comment]
Issue solved in a different way
