### ISSUE TITLE
truncating data

### ISSUE THREAD

**Issue by jkkenley** [DCAN-Labs/dcan_bold_processing#24]
I am using docker version:
dcanlabs/abcd-hcp-pipeline:v0.0.3

When I run the docker I see the following screen output:
raceback (most recent call last):
  File "/app/run.py", line 364, in <module>
    _cli()
  File "/app/run.py", line 67, in _cli
    return interface(**kwargs)
  File "/app/run.py", line 360, in interface
    stage.run(ncpus)
  File "/app/pipelines.py", line 588, in run
    self.teardown(result)
  File "/app/pipelines.py", line 534, in teardown
    self.__class__.__name__)
Exception: error caught during stage: FMRIVolume

The log files within the FMRIVolume folder indicate the error is:
json:
    "stage erminated with exit code [0, 1, 1, 0]"
.err:
    ** ERROR (nifti_image_read): short header read '/output/sub-test1/ses-None/files/task-rest02/task-rest02_gdc.nii.gz'
    ** ERROR: nifti_image_open(/output/sub-test1/ses-None/files/task-rest02/task-rest02_gdc): bad header info
    ERROR: failed to open file /output/sub-test1/ses-None/files/task-rest02/task-rest02_gdc
    Cannot open volume /output/sub-test1/ses-None/files/task-rest02/task-rest02_gdc for reading!

When I review these files they have been truncated down from there original size from 383 frames to 233 and I don't know why.

Thank you for your help.
Jeanette

**Comment by lundq163** [comment]
Hi Jeanette, 
I would recommend using this docker version: dcanumn/abcd-hcp-pipeline:v0.1.3
Please update this thread if you continue running into the same error, thanks!

**Comment by lundq163** [comment]
correct

**Comment by jkkenley** [comment]
Thanks!


The materials in this email are private and may contain Protected Health Information. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying, distribution or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone or return email.

________________________________

**Comment by jkkenley** [comment]
That worked!

Thanks for much!

Does the docker have anything like the below which could be used as a QC measure for registration of the bold after distortion correction?
[cid:5abbf5fc-7b22-4074-b6d1-dcb1e5148157]

Is this file the closest?

[cid:c1bdeb66-7c27-45aa-bd59-21d92eaf7ab7]

The materials in this email are private and may contain Protected Health Information. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying, distribution or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone or return email.

________________________________

**Comment by hough129** [comment]
@jkkenley we cannot see the images you have attached because you are responding via email. Can you respond via github with the images you attached so we can understand what you are asking?

**Comment by lundq163** [comment]
@jkkenley, I am going to close this issue for now. Please respond whenever if you feel like you still need any assistance
