### ISSUE TITLE
MATLAB system call to cat (with appending >>) doesn't work for all shells

### ISSUE THREAD

**Issue by ericearl** [DCAN-Labs/dcan_bold_processing#3]
On this line:

https://github.com/DCAN-Labs/dcan_bold_processing/blob/v4.0.3/matlab_code/analyses_v2.m#L172

The append (`>>`) is special to BASH shells.  To make this more generic, especially considering the line right before it, this should be turned into only a stdout redirect (`>`) to be more flexible with other shells.

**Comment by hough129** [comment]
@madisoth informed me that this fix is only important for those running this codebase outside of a container. This most likely will not be addressed unless it becomes necessary. I will leave it open as a reminder.

**Comment by LuciMoore** [comment]
@audreymhoughton I'm closing this for now as we are moving towards utilizing fmriprep moving forward
